### ISSUE TITLE
Crash report: Failed to connect to api.ashcon.app -> invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by KevBelisle** [dirien/minecraft-prometheus-exporter#136]
```
ts=2022-02-09T14:41:22.079Z caller=exporter.go:450 level=error msg="Failed to connect to api.ashcon.app" err="Get \"https://api.ashcon.app/mojang/v2/user/0e3d82b5-ddfb-42ad-9cdd-ba39766ed255\": read tcp IP.ADD.RESS.HERE:44562->IP.ADD.RESS.HERE:443: read: connection reset by peer"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x83c8e4]

goroutine 69201 [running]:
github.com/minecraft-exporter/pkg/exporter.(*Exporter).getPlayerStats(0xc000242240, 0x1)
        /home/runner/work/minecraft-prometheus-exporter/minecraft-prometheus-exporter/pkg/exporter/exporter.go:453 +0x564
github.com/minecraft-exporter/pkg/exporter.(*Exporter).Collect(0xc000242240, 0xc0002f6f60)
        /home/runner/work/minecraft-prometheus-exporter/minecraft-prometheus-exporter/pkg/exporter/exporter.go:826 +0x21a
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:446 +0x102
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:538 +0xb4d
```

**Comment by dirien** [comment]
Hi @KevBelisle,

it works for me. I tried the to curl your URL and via the exporter itself.

I use `https://github.com/Electroid/mojang-api` and maybe there was a downtime there? Or you need maybe a proxy or open the egress rule on your server?

```bash
 curl https://api.ashcon.app/mojang/v2/user/0e3d82b5-ddfb-42ad-9cdd-ba39766ed255
{
  "uuid": "0e3d82b5-ddfb-42ad-9cdd-ba39766ed255",
  "username": "kaitcht",
  "username_history": [
    {
      "username": "kaitcht"
    }
  ],
  "textures": {
    "custom": true,
    "slim": false,
    "skin": {
      "url": "http://textures.minecraft.net/texture/c46c45a796f67477821a0ce0d30c4ae3bbcf636245cff87ccbaeb7edc64d707e",
      "data": "iVBORw0KGgoAAAANSUhEUgAAAEAAAAAgCAYAAACinX6EAAAJw0lEQVR4Xs2ZWYxUxxWGr/ISTBhFWYDMThwzQExPTzcM2HFI7NgYJ0Rmiw0mBseOrSyWbcwyGzM9DQNkVZ7yYCmSlYjXyIoYxuz0NmYZK1Ge/Jg3xy95NM6DSU7Od+qe9p3bkGEyI5SSjqpuVd2q8/9nqbrdUTRDWb70Hun60kL5astnQt0a6kz7onpfUr6y5B65b2kQntPrzbb4urnOJlnZvFCWfXHBtP3S8+e99HQskvsV9H0KzNtsvHypktC2SKRaNLAo1va5T5vQpk/KhTkrmCY4qzrcVQJ8IweO5bEEbawttaPyjz++In/5zRaZPLbRhDZ9Uh6cs4Lss0L3u3dJ8CgX94T0/HkvbIL7Ua9ua3R5qR2Rv735nAEvjT5sQps+KQ3NWUEI9708rDoTYZCeP+/FNk6w3/mFBSarNP5XtSgB1aO3J6AyMmcFu5WAjBKf1frLixeY5em7qwQgvik1HkEyzC9rMpC3DYHa2JwVJO848dQkXjfCXSEAKzsJKOPxT3uF1lI5LB+XigYYqyO0P75w0BJker3ZFt8bwQsgnrrjbhHgmxP/AHZPwB2pZfKEkSDVI5r0hrStdXU09FXmngPcA5KC51mtnpieP+vii967eHqWhWU28OyPeDKk9vM++Y7P9fM616lxGycs1krO9XnkEvZa1Ry8yvfw4871wgCehP1u4pK+G6AX+tFmPcLFDZfWwwhIg08KivCy1I4F0aSHhRkD8OoEQQDAOmzKmrwHQN/DlXKFb3WquLCGj3MMJsc8LJPeASl4pYeoC4CToH1vfzdKWtg73Qo8S2U0AC8P25lvbl47rv2DeswNTtvMWeaSZJsvC8mS/luRDECUdk/iyIMkBO90L0APngHJO+65DpZnn5Nc33HwXvLo9L3tXe9wBf/++52WvHAbA14p1Bcy0PrspNGGEGtXC/LByb3mzr4mN0VqMrcnzaRy6eOM446aMWoK63nb593uOdlHzfENLjyAta0vFT42USrD8a3umLz/ZiDAJ0pJk5mWMO+oXXxQ0ErsAVhKyoeVgD2W+OgL1+SR4DW6Hn14hM3V/VBISgNGdFr5+Si+HyHIc9LTEfKTTeS6CijL4iirVn7/D7vrE60PEtTCUina9dbCoRIE6+KKH5x81sBz/w+ewomgUh2z+4CTUA8pOyVG5w3wrQr7eWhQPBf4mHWaQsS1KlhPdKqcx4h5RilYNemygPI27EpZrV1BIHQsEMURaaRCbnw8kj8Yg9Dy3I/J/1Y8lyQLuk7rMEvauU1yG4utN1IHjXj8YGn/HEb8MmLkmUVHYjJx/djy9gwBx0Md5w0jRD1pmjL/DyW/65p0bzsvPU9VJfdUTbpaPystn19Yr9Pz02Vq9CXpUl7/dbkgH731E/nnRL/cvDxgfadf3y25p2vSvfVtye28Im35/bLmmXcl8+S47leRnu+VZlz/nK4zpvIrlZqKJ+bgZXO/ehsB2e0XTaHsjovTwFOn56fLuIIE7Ifjr8p7xQ3y5/718uGfXra+84f2KOApA5zdfl5ac6/J6idPGRn5Xdcls2VixvWLus43VL6t0g8BlnNiD67Mg0dltoybJVAMEmbrARcO7TWwH030yXuFh+Sv/Q/IjdP7rW9i//elZ8dlXb9sJHSuH5GMegP7dW87K91KSnq9dMH6j6lsVilAQD3MyGEnZnx/xpLfedUUzKqiuacnZ+0BlcHnDezN0pjceOuncmN8v9wsH/kkBNTa3VvPGLntawd0j3fM47LbL1jIpddLF9x+VOWIypQRwKWsYEcquSw9f8bSve2cdPQOCsDbte7oHTKLAB4FO9YNx8r2m+JYrDW3LyivYK6pEr9QOapyXqU08AP5pdYARrF/6xFK+5AK3nFR61+rHIAQlbMHnrVn5iRlWOXayIu2Ju8ei0LMvx2FvdizrDIRj/N8lXdUTkQhR7B+Gm9DAWxL9mXJa2xCApanTRLkmSRFu2PdSCBgy2kT2oxhBTYkHmmf2veMEUCfgzmoMqRyZfiHpiAAAHgZ6X/OlD+uciYKgH4ej+Mxh7Veq/KdeB3616s8HoU1+1S+q7IuHqePHNGrMhDdAQHEOtkYkOb26oZYGfCAxBNo4xnEqbsrYULMsumDKo9GwRLnDu6Rh7RGcFMIQCEUvl54yeZ8PQqgIOmqWhlw9BXjPtb7mkrt8As2n7mMQzKWZa1H4vmQxVz68CSeef+BKJwWabwNhRCAALI/4PO7pqwNaAcPEcwhXpkDaZABacQjG3pSmlKQWINEhfWk/Cl5Qutvqozv223esUFlYxTcFitDAABYC1cHLOsRTngMVsZrylHwEPZhLi5eigIxjBNeeCHEmy7RHRBACBDnAPMY98TEfYCjycMkeISO7bgUEpn2n41CPGOpisoZjemRKACZjIIHDLqCfXvl3VhBnsdVqkPPmyUhhpC4ELcRcgDnPlYnRHj3ShQsyzhj78TPkF1WqUaBHHTiOQW3sRDHrT2vhVhXQFh/+SO/lRWP/c4sDVjIae15NeQHPa9XbjopXY++YePEbTEWAF0rvGhkEKuXouABALCLy9ALltQADwmQN6luzlxIg8BT8bs/o635hPeIecIA0KzN86YoWJ598Th3ebyF+CcsIC0Ft7Hgyrg3lseqEAAwtzzxThuSyPqWKzT2IYIznU1xVxRE2Uua1FCQEAAIHoD7E7MckcUoKMw7EAEpa6IACE9hPQAACG/ymCanYFnmeA4g4ZGDCBnmkAPYk5BDB0hM420oZHyONC4mxDs111U7rxWoX1QsUWriyykBdlXmrqDkYBUAsWkxCi4NGAjBLSEAMADgGHSAKAgBgGQci7mnkNURLk6870T+L5LG21BIgu1r+qQ582O9mRUMKM/UPHfobY02dwW/H1h+UHKoiVniHUsQ8xx1uB7EeA44EQXLMkaYkKCwHjHNqQFRiB+DhANElDUJRvEahBIhRZ4gDPAMnrkbQBDWJ4QIK0IDndAtjbehtOVeN8APZ1qkd/liq5GNuTb5VrZVNuXbZPPaDiMhLS3ZVyxL45YQcF2lVCrZ5ihFhkZ5FMZ9GSNpMReQvEsfZLEGCnOZYT7jjKUtOltJ420oDhiQm3s7rO1XX9rrupbIgyuXWnvD/c2yVkl6XMnheVO+XZqamuymSI2QQ7yN1ZBPxq7X2yRUbxNW3q7P1XC0NfxDh7u+fbbz8RP/LskPtPYR5J/jfG4n597BP1Ppj53Z1oBqyx+wXBHuCuHu4P18/RE6JE9ukIQV4NvXHKrfL0iyhFRz5kfmjRy13VvPam7qMxD2i5T9/xD/KuW/NjFmRPAhxG8ZQ2Gu/RbBDzsz/zn7H4M61xqLx+e0AAAAAElFTkSuQmCC"
    },
    "raw": {
      "value": "ewogICJ0aW1lc3RhbXAiIDogMTY0NDYwODcyMjI4NywKICAicHJvZmlsZUlkIiA6ICIwZTNkODJiNWRkZmI0MmFkOWNkZGJhMzk3NjZlZDI1NSIsCiAgInByb2ZpbGVOYW1lIiA6ICJrYWl0Y2h0IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M0NmM0NWE3OTZmNjc0Nzc4MjFhMGNlMGQzMGM0YWUzYmJjZjYzNjI0NWNmZjg3Y2NiYWViN2VkYzY0ZDcwN2UiCiAgICB9CiAgfQp9",
      "signature": "qvtdX/1Yw1knP6hQE6cIBUG3ar+qA61GScuOwOwHQ+ipG7HJ4xwVwUPoWaCz69LKcwPAyUjMOLCzmKmN5+G4ip/Ajw/6ynC87GeKfT/rH5DjS6AxyEZAWW4pmWWmD3lizS5B/jD1QSQgd2KZfWK6tnnCeHxlILqY1b2Tz1/3bYxre0xCAmrOusj9xcO7QJxUJcQNUwdbUqMhUYAu0LHlry4s6NnKaeIATDtZnSX8bKBjmpmECNiroojsnpJakbGzIwkFg2rGBIwsh2aT9vVskfJhGFSUeZU7XQBWRH4Qh5Exzznd+ob8yCnrudfm4HlL+5Oq7v1juOBxFk/IMozotnk1LgqEfbLCDm6e5/qzcFS4LW9oOxc4lVlVDVbK6aLx/OKpMGwovl4hS5jGKeBV+MbEiDRJy8YkcuZWaEhmxD34Tvuu+8w/Kebq2qAPs7m2N9boLH7r2UOhPJcMHKz7+jahUDhJ0KLLG/tReKFCV0Z+1eIDBqmXLoLUVAnxHvWlQA8JESiOivm7pDp/VRYq1HPwFA7r93FVMoF/t9eMn6YR40ubD8n5Lbpapdn7qjaiS973a8kt0Z9Yv4bRDfAbPAkUuTfqY8mctdD3KVll/74NM1Zpj347hJb48usmG9APfmQ8VZ1Wm6Jfm/oIGi/y8p+OlUBy5J1MdhEbGSXmXBc="
    }
  },
  "legacy": true,
  "created_at": null
}%
```

Let me know, how I may can help.

**Comment by KevBelisle** [comment]
To be clear: this is working fine and is very stable.

I’m assuming that that one request failed for some reason, perhaps a transient error on the API side.

My suggestion is that this should be caught and handled gravefully (perhaps simply returning a 500 error), instead of crashing the application.

**Comment by dirien** [comment]
ok now I got it @KevBelisle 😅 

Done fixed it.
